ecommerce_lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/marco.mazzei/engenharia-dados-2026/data/dbt_dev.duckdb
      threads: 4
      extensions:
        - httpfs
      settings:
        # Configurações do MinIO como fonte S3
        s3_endpoint: 'localhost:9000'
        s3_access_key_id: 'minioadmin'
        s3_secret_access_key: 'minioadmin123'
        s3_use_ssl: false
        s3_url_style: 'path'

    prod:
      type: duckdb
      path: /Users/marco.mazzei/engenharia-dados-2026/data/dbt_prod.duckdb
      threads: 8
      extensions:
        - httpfs
      settings:
        s3_endpoint: 'localhost:9000'
        s3_access_key_id: 'minioadmin'
        s3_secret_access_key: 'minioadmin123'
        s3_use_ssl: false
        s3_url_style: 'path'
